version: "3.9"
services:
  blog_db:
    container_name: blog_db
    image: mysql
    restart: always
    ports:
        - "3306"
    enviroment:
        MYSQL_DATABASE: blogx
        MYSQL_ROOT_PASSWORD: blogx
        MYSQL_USER: blogx
        MYSQL_PASSWORD: blogx
  blog_app:
    container_name: blog_app
    image: heryfik/laravel:latest
    ports:
        - 9000:9000
    depends_on:
        - blog_db